name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm config set //registry.npmjs.org/:_authToken "${{ secrets. NPM_TOKEN }}" && npm ci
      - name: Run production build
        run: |
          npm run build-prod
      - name: Generate package-lock.json
        run: |
          npm i --package-lock-only
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update lib to version ${{ steps.package-version.outputs.current-version}}
          committer_name: tyk-ui bot
          committer_email: tyk-ui-bot@tyk.io
      - name: Publish lib to npm
        run: |
          echo "running npm publish"