name: Build and Publish

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-lib:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm config set //registry.npmjs.org/:_authToken "${{ secrets.NPM_TOKEN }}" && npm ci --ignore-scripts
          npm install esbuild@0.21.5
      - name: Run production build
        run: |
          npm run build-prod
      - name: Generate package-lock.json
        run: |
          npm i --package-lock-only
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b  # main
      - name: Push changes
        run: |
          git config --local user.email "tyk-ui-bot@tyk.io"
          git config --local user.name "tyk-ui bot"
          git add .
          git commit -m "Update lib to version ${{ steps.package-version.outputs.current-version}}"
          git push
      - name: Publish lib to npm
        uses: JS-DevTools/npm-publish@22595ff8c4d0d9f53cef0656fbb90fbe06ee885c  # v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}

    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
